---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Analysis of Convergence Metrics

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(coda)
library(trend)

# import games.csv and convergence_metrics.csv

head(convergence_metrics)
players <- convergence_metrics$player %>%
            unique()
head(players)
plot_data <- convergence_metrics %>%
              filter(player == players[1])
plot1 <- ggplot(data = plot_data, aes(`win_ratio`)) +
        geom_histogram(binwidth = 0.001) +
        theme_minimal()

plot2 <- ggplot(data = plot_data, aes(`profitability_per_hand`)) +
        geom_histogram(binwidth = 5) +
        theme_minimal()
plot1 + plot2

plot3 <- ggplot(data = plot_data, aes(`win_ratio_cumm`)) +
        geom_histogram(binwidth = 0.00001) +
        theme_minimal()

plot4 <- ggplot(data = plot_data, aes(`profitability_per_hand_cumm`)) +
        geom_histogram(binwidth = 0.1) +
        theme_minimal()
plot3 + plot4

win_ratio_acf_values <- acf(plot_data$win_ratio)
profitability_per_hand_acf_values <- acf(plot_data$profitability_per_hand)
win_ratio_ess <- effectiveSize(plot_data$win_ratio)
profitability_per_hand_ess <- effectiveSize(plot_data$profitability_per_hand)

win_ratio_cumm_acf_values <- acf(plot_data$win_ratio_cumm)
profitability_per_hand_cumm_acf_values <- acf(plot_data$profitability_per_hand_cumm)
win_ratio_cumm_ess <- effectiveSize(plot_data$win_ratio_cumm)
profitability_per_hand_cumm_ess <- effectiveSize(plot_data$profitability_per_hand_cumm)
```
# Finalised metrics
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(trend)
library(TTR)
library(randtests)
library(tseries)

players <- convergence_metrics$player %>%
            unique()
game <- games[-1, ]
columns <- colnames(game)
total_players <- (length(columns) - 3) / 2 # 2 columns for each player signifying the bankroll and the tendency index
game_long <- game %>%
      pivot_longer(cols = columns[2:(2 + total_players - 1)],
             names_to = "Player",
             values_to = "Score")

plot <- ggplot(data = game_long,
                   aes(x = hand_no, y = Score, colour = Player)) +
      geom_line() +
      theme(legend.position = "bottom")
#plot

size_limit <- 100
step <- nrow(game) / size_limit
truncated_game <- game[seq(1, nrow(game), by = step), ]
truncated_game_long <- truncated_game %>%
      pivot_longer(cols = columns[2:(2 + total_players - 1)],
             names_to = "Player",
             values_to = "Score") %>%
      group_by(Player) %>%
      #mutate(Score = EMA(Score, n = 100)) %>%
      ungroup()

plot1 <- ggplot(data = truncated_game_long,
                   aes(x = hand_no, y = Score, colour = Player)) +
      geom_line() +
      theme(legend.position = "bottom")
plot1

player_bankroll <- truncated_game_long %>%
    filter(Player == !!players[1]) %>%
    pull(Score)
plot(player_bankroll, type = "l", col = "blue", 
     xlab = "Index", ylab = "Value", 
     main = "Plot")
grid()
running_average <- cumsum(player_bankroll) / seq_along(player_bankroll)
lines(running_average, type = "l", col = "red", lwd = 2)

results <- mk.test(running_average)
print(results)
#results <- cox.stuart.test(running_average)
#print(results)
#adf_results <- adf.test(running_average) # stationarity of a time series
#print(adf_results)
#sen_slope <- sens.slope(running_average)
#print(sen_slope)

player_bankroll_diff <- truncated_game_long %>%
    group_by(hand_no) %>%
    transmute(score_diff = Score[Player == !!players[1]] - Score[Player == !!players[2]]) %>%
    unique()
plot(player_bankroll_diff$score_diff, type = "l", col = "blue", 
     xlab = "Index", ylab = "Value", 
     main = "Diff Plot")
grid()

mean_diff <- mean(player_bankroll_diff$score_diff)
sd_diff <- sd(player_bankroll_diff$score_diff)
cohens_d <- mean_diff / sd_diff
print(paste("Cohen's d:", round(cohens_d, 3)))

spearman <- cor(running_average, seq_along(running_average), method = "spearman")
print(paste("Spearman rank correlation:", spearman))

analysis_metrics <- data.frame(
  p = results$p.value,
  S = results$estimates[1],
  rho = spearman,
  d = cohens_d
)
matchup <- gsub(".*\\((.*)\\).*", "\\1", players)
rownames(analysis_metrics) <- paste(matchup, collapse = " ")
```
# Rolling window analysis
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(trend)
library(TTR)
library(randtests)

size_limit <- 10000

players <- convergence_metrics$player %>%
            unique()
analysis_metrics <- data.frame(
      player = character(),
      S = numeric(),
      p = numeric(),
      Z = numeric(),
      "0.10" = logical(),
      "0.05" = logical(),
      "0.01" = logical(),
      stringsAsFactors = FALSE
    )

game <- games[-1, ]
columns <- colnames(game)
total_players <- (length(columns) - 3) / 2 # 2 columns for each player signifying the bankroll and the tendency index
game_long <- game %>%
      pivot_longer(cols = columns[2:(2 + total_players - 1)],
             names_to = "Player",
             values_to = "Score")

plot <- ggplot(data = game_long,
                   aes(x = hand_no, y = Score, colour = Player)) +
      geom_line() +
      theme(legend.position = "bottom")
#plot

step <- nrow(game) / size_limit
truncated_game <- game[seq(1, nrow(game), by = step), ]
print(nrow(truncated_game))
truncated_game_long <- truncated_game %>%
      pivot_longer(cols = columns[2:(2 + total_players - 1)],
             names_to = "Player",
             values_to = "Score")

plot1 <- ggplot(data = truncated_game_long,
                   aes(x = hand_no, y = Score, colour = Player)) +
      geom_line() +
      theme(legend.position = "bottom")
plot1

truncated_game_long <- truncated_game_long %>%
  group_by(Player) %>%
  #mutate(Score = EMA(Score, n = 100)) %>%
  filter(!is.na(Score)) %>% # Remove NA values
  ungroup()

plot2 <- ggplot(data = truncated_game_long,
                   aes(x = hand_no, y = Score, colour = Player)) +
      geom_line() +
      theme(legend.position = "bottom")
plot2

player_bankroll <- truncated_game_long %>%
  filter(Player == !!players[1]) %>%
  pull(Score)

#results <- smk.test(ts(player_bankroll, start = 1, frequency = 100))
#results <- mk.test(player_bankroll)
#print(results)

plot(player_bankroll, type = "l", col = "blue", 
     xlab = "Index", ylab = "Value", 
     main = "Plot")
grid()
running_average <- cumsum(player_bankroll) / seq_along(player_bankroll)
lines(running_average, type = "l", col = "red", lwd = 2)
library(Kendall)

# Define window size (e.g., 500 observations)
window_size <- 500
rolling_trends <- sapply(1:(length(player_bankroll) - window_size), function(i) {
  mk_test <- MannKendall(player_bankroll[i:(i + window_size)])
  return(mk_test$tau)  # Use Kendall's tau to measure trend strength
})

# Plot rolling trend results
plot(rolling_trends, type = "l", main = "Rolling Kendall's Tau",
     xlab = "Window Start Index", ylab = "Kendall's Tau")
```
